import React from "react";
import "./globals.css";
import { AuthProvider } from "@/components/providers/AuthProvider/AuthProvider";
import { Toaster } from "sonner";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body>
        <AuthProvider>
          {children}
          <Toaster theme="light" />
        </AuthProvider>
      </body>
    </html>
  );
}
